/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelConection.conexaoBD;

/**
 *
 * @author andre e taila
 */
public class TelaPrincipal extends javax.swing.JFrame {

       conexaoBD conecta = new conexaoBD();
       FormMedico tela = new FormMedico();
       FormUsuario telausu = new FormUsuario();
       
       
       
    public TelaPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conecta.conexao();
    }

    TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPainelFundo = new javax.swing.JLabel();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternalFrame = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonFecharBemVindo = new javax.swing.JButton();
        jButtonCadUsuarios = new javax.swing.JButton();
        jButtonCadMedico = new javax.swing.JButton();
        jButtonCadPacientes2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadMedicos = new javax.swing.JMenuItem();
        jMenuItemCadPacientes = new javax.swing.JMenuItem();
        jMenuItemCadEnfermeiras = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenuRelatórios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-login-admin.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternalFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelInternalFrame.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("cadastros ");
        jPanelInternalFrame.add(jLabel2);
        jLabel2.setBounds(30, 10, 130, 20);

        jButtonFecharBemVindo.setBackground(new java.awt.Color(0, 0, 255));
        jButtonFecharBemVindo.setText("Sair");
        jButtonFecharBemVindo.setToolTipText("Fehcar tela de Bem Vindos");
        jButtonFecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBemVindoActionPerformed(evt);
            }
        });
        jPanelInternalFrame.add(jButtonFecharBemVindo);
        jButtonFecharBemVindo.setBounds(640, 120, 90, 23);

        jButtonCadUsuarios.setBackground(new java.awt.Color(0, 0, 255));
        jButtonCadUsuarios.setText("Usuários");
        jButtonCadUsuarios.setToolTipText("Cadastro de pacientes");
        jButtonCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuariosActionPerformed(evt);
            }
        });
        jPanelInternalFrame.add(jButtonCadUsuarios);
        jButtonCadUsuarios.setBounds(20, 80, 90, 23);

        jButtonCadMedico.setBackground(new java.awt.Color(0, 0, 255));
        jButtonCadMedico.setText("Médico");
        jButtonCadMedico.setToolTipText("Cadastro de médico");
        jButtonCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicoActionPerformed(evt);
            }
        });
        jPanelInternalFrame.add(jButtonCadMedico);
        jButtonCadMedico.setBounds(20, 40, 90, 23);

        jButtonCadPacientes2.setBackground(new java.awt.Color(0, 0, 255));
        jButtonCadPacientes2.setText("Pacientes");
        jButtonCadPacientes2.setToolTipText("Cadastro de pacientes");
        jButtonCadPacientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacientes2ActionPerformed(evt);
            }
        });
        jPanelInternalFrame.add(jButtonCadPacientes2);
        jButtonCadPacientes2.setBounds(20, 120, 90, 23);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternalFrame);
        jPanelInternalFrame.setBounds(0, 30, 750, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("sistema de gerenciamento de:");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 30);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 10, 770, 430);
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(60, 440, 140, 20);

        jLabel4.setText("Usuário");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 440, 50, 20);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-login-admin.jpg"))); // NOI18N
        jLabelFundoTelaPrincipal.setText("jLabel1");
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, -20, 780, 480);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadMedicos.setText("Médicos");
        jMenuItemCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedicosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadMedicos);

        jMenuItemCadPacientes.setText("Pacientes");
        jMenuItemCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadPacientes);

        jMenuItemCadEnfermeiras.setText("Enfermeiras");
        jMenuItemCadEnfermeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEnfermeirasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadEnfermeiras);

        jMenuItemCadUsuarios.setText("Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadUsuarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatórios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatórios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(789, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedicosActionPerformed

           try {
               conecta.executasql("select * from usuarios where usu_nome='" +jLabelUsuario.getText()+"'"); // verificando usuário
               conecta.rs.first();
               if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                   if(tela==null){
                       tela = new FormMedico();
                       tela.setVisible(true);                       // não deixar abrir mais que 1 tela;;
                       tela.setResizable(false);
                   }else{ 
                       tela.setVisible(true);
                       tela.setResizable(false);
                   }
           //    FormMedico tela = new FormMedico();
           //    tela.setVisible(true);
               } else{
                   JOptionPane.showMessageDialog(rootPane, "você não tem permissão para acessar essa tela. verifique com o ADMINISTRADOR");
               }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"não foi possivel entrar em cadastro de médico"+ex);
           }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadMedicosActionPerformed

    private void jMenuItemCadEnfermeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEnfermeirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadEnfermeirasActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jButtonCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicoActionPerformed
           try {
               conecta.executasql("select * from usuarios where usu_nome='" +jLabelUsuario.getText()+"'"); // verificando usuário
               conecta.rs.first();
               if(conecta.rs.getString("usu_tipo").equals("Administrador")){
                   if(tela==null){
                       tela = new FormMedico();
                       tela.setVisible(true);                       // não deixar abrir mais que 1 tela;;
                       tela.setResizable(false);
                   }else{ 
                       tela.setVisible(true);
                       tela.setResizable(false);
                   }
           //    FormMedico tela = new FormMedico();
           //    tela.setVisible(true);
               } else{
                   JOptionPane.showMessageDialog(rootPane, "você não tem permissão para acessar essa tela. verifique com o ADMINISTRADOR");
               }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"não foi possivel entrar em cadastro de médico"+ex);
           }        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonCadMedicoActionPerformed

    private void jButtonCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuariosActionPerformed
         try {
               conecta.executasql("select * from usuarios where usu_nome='" +jLabelUsuario.getText()+"'"); // verificando usuário
               conecta.rs.first();
               if(conecta.rs.getString("usu_tipo").equals("Administrador")){
               if(tela==null){
                telausu = new FormUsuario();
                telausu.setVisible(true);                       // não deixar abrir mais que 1 tela;;
                telausu.setResizable(false);
                   }else{ 
                telausu.setVisible(true);
                telausu.setResizable(false);
                   }
                //FormUsuario tela = new FormUsuario();
                //tela.setVisible(true);
               } else{
                   JOptionPane.showMessageDialog(rootPane, "você não tem permissão para acessar essa tela. verifique com o ADMINISTRADOR");
               }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"não foi possivel entrar em cadastro de médico");
           }
    }//GEN-LAST:event_jButtonCadUsuariosActionPerformed

    private void jButtonFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBemVindoActionPerformed
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharBemVindoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacientesActionPerformed
         FormPaciente tela = new FormPaciente();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCadPacientesActionPerformed

    private void jButtonCadPacientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacientes2ActionPerformed
 FormPaciente tela = new FormPaciente();
 tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadPacientes2ActionPerformed

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
          try {
               conecta.executasql("select * from usuarios where usu_nome='" +jLabelUsuario.getText()+"'"); // verificando usuário
               conecta.rs.first();
               if(conecta.rs.getString("usu_tipo").equals("Administrador")){
               if(tela==null){
                telausu = new FormUsuario();
                telausu.setVisible(true);                       // não deixar abrir mais que 1 tela;;
                telausu.setResizable(false);
                   }else{ 
                telausu.setVisible(true);
                telausu.setResizable(false);
                   }
                //FormUsuario tela = new FormUsuario();
                //tela.setVisible(true);
               } else{
                   JOptionPane.showMessageDialog(rootPane, "você não tem permissão para acessar essa tela. verifique com o ADMINISTRADOR");
               }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"não foi possivel entrar em cadastro de médico");
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadMedico;
    private javax.swing.JButton jButtonCadPacientes2;
    private javax.swing.JButton jButtonCadUsuarios;
    private javax.swing.JButton jButtonFecharBemVindo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadEnfermeiras;
    private javax.swing.JMenuItem jMenuItemCadMedicos;
    private javax.swing.JMenuItem jMenuItemCadPacientes;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenu jMenuRelatórios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternalFrame;
    // End of variables declaration//GEN-END:variables
}
